# Generated by Django 3.2.22 on 2023-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='info_dest',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
